### ISSUE TITLE
Name '__bpy_property' is not defined

### ISSUE THREAD

**Issue by LinyeNinja** [UuuNyaa/blender_mmd_tools#10]
When activating addon under blender 3.0 in linux mint (standalone version), I get the error:

Traceback (most recent call last):
[...]
  File "/home/-/.config/blender/3.0/scripts/addons/mmd_tools/__init__.py", line 22, in register_wrap
    bl_props = {k:v for k, v in cls.__dict__.items() if isinstance(v, __bpy_property)}
  File "/home/-/.config/blender/3.0/scripts/addons/mmd_tools/__init__.py", line 22, in <dictcomp>
    bl_props = {k:v for k, v in cls.__dict__.items() if isinstance(v, __bpy_property)}
NameError: name '__bpy_property' is not defined

**Comment by UuuNyaa** [comment]
I was not able to reproduce the problem in my environment.
Please let me know the detailed version of MMD Tools.

**Comment by UuuNyaa** [comment]
There is no reply.
