### ISSUE TITLE
MMD Tool impossible install in Blender 3.6

### ISSUE THREAD

**Issue by Man-with-the-bread** [UuuNyaa/blender_mmd_tools#107]
I tried to install it in Blender 3.6 in the end it is installed but you can not enable it, when trying to enable this addon Blender complains about an error

The error itself will be attached below:

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Seiwer\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_tools\__init__.py", line 22, in <module>
    auto_load.init()
  File "C:\Users\Seiwer\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\Seiwer\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\Seiwer\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Seiwer\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_tools\core\morph.py", line 7, in <module>
    from mmd_tools.bpyutils import ObjectOp, SceneOp, TransformConstraintOp
ImportError: cannot import name 'ObjectOp' from 'mmd_tools.bpyutils' (C:\Users\Seiwer\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mmd_tools\bpyutils.py)

`

**Comment by UuuNyaa** [comment]
Does the installation fail even if you strictly follow the installation instructions at the following URL?
https://mmd-blender.fandom.com/wiki/MMD_Tools#Installation
