### ISSUE TITLE
camera's field of view angle is incorrect in the rendering result

### ISSUE THREAD

**Issue by ggvy** [UuuNyaa/blender_mmd_tools#19]
I don't know what I did.When I try to import camera data in different scenes，I always find that the field of view angle of the rendered result is different from that of the preview, and it is obviously incorrect.I tried to reload the data.However, when I restart blender, the problem still exists.
The following is the information in the console：

File "C:\Users\29810\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_tools\properties\camera.py", line 42, in _getIsPerspective
Traceback (most recent call last):
  File "C:\Users\29810\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_tools\properties\camera.py", line 50, in _setIsPerspective
    cam = __get_camera(prop.id_data)
  File "C:\Users\29810\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_tools\properties\camera.py", line 16, in __get_camera
    depsgraph = __find_depsgraph(empty)
  File "C:\Users\29810\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_tools\properties\camera.py", line 25, in __find_depsgraph
    if obj == view_layer.depsgraph.objects.get(obj.name):
AttributeError: 'NoneType' object has no attribute 'objects'

I don't know the cause of the problem and how to solve it.I wonder if you have a solution.

**Comment by UuuNyaa** [comment]
To me, it looks like the message that appears when mmd_tools fails to initialize.

Try the following:
- https://mmd-blender.fandom.com/wiki/MMD_Tools/Release_Notes#How_to_update_from_v1
- https://mmd-blender.fandom.com/wiki/Why_can%27t_I_reinstall_the_add-ons%3F

**Comment by ggvy** [comment]
Thank you.But this problem still exists.I have deleted the original mmd tool,and reinstall and save the startup file.
I think I may not explain some details clearly:
In my blender file.I have two scenes.However,I only have one camera.Because I used the "Link to Scene" function.
Like the following:
![scene](https://user-images.githubusercontent.com/42503581/153740967-7a1a2cc3-faf4-4d06-a3cc-7b882f44495a.png)
![scene1](https://user-images.githubusercontent.com/42503581/153740972-8bf808f6-7d5c-48a7-9af1-e7a386cacdf8.png)
![scene2](https://user-images.githubusercontent.com/42503581/153740977-7844fd28-2454-4dde-886d-3afc8ef6b1f5.png)
I don't know if it's because of this.However,because I personally prefer to use "Scene",so I wonder if you have any other solution.

**Comment by nagadomi** [comment]
MMDCamera controls `Camera.data.lens` via `MMDCamera.angle`'s set/get  handler, which does not work properly under some conditions. I think it is a bad practice, but I don't know if there is any reason to use it or if it is just outdated code.
By using driver instead, it may be possible to remove the code that accesses depsgraph and work around this problem. (just an idea, not tested)

**Comment by ggvy** [comment]
Thank you. I'll try again.

**Comment by UuuNyaa** [comment]
@ggvy I solved this problem with a3ef6c777983174c3902fe08ea61c7f82e5988dd .
Please test the latest main branch.
1. manually update to **main** branch  <br> ![image](https://user-images.githubusercontent.com/70152495/193330894-30780163-7bce-4e43-9e21-3f1cc06e5840.png)
2. restart Blender
3. load a scene containing MMD camera motion

**Comment by rintrint** [comment]
Does this issue still happen?

**Comment by rintrint** [comment]
Blender's Link feature still lacks stability in edge cases and needs further refinement. This issue is beyond MMD Tools' scope. If I have misunderstood anything, please let me know.
