### ISSUE TITLE
error no attribute 'proxy' in 3.2

### ISSUE THREAD

**Issue by listelin** [UuuNyaa/blender_mmd_tools#48]
## 事象
Blender3.2RCでMMD>シーン設定＞リジッドボディ＞＞ワールドを更新を実行するとコンソールに以下のエラーが発生します。
```
Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\operators\rigid_body.py", line 531, in execute
    for r in _references(i):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\operators\rigid_body.py", line 515, in _references
    if obj.proxy:
AttributeError: 'Object' object has no attribute 'proxy'
Error: Python: Traceback (most recent call last):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\operators\rigid_body.py", line 531, in execute
    for r in _references(i):
  File "C:\Users\a\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\operators\rigid_body.py", line 515, in _references
    if obj.proxy:
AttributeError: 'Object' object has no attribute 'proxy'
```

## 原因
3.2でProxyが削除されたため
https://wiki.blender.org/wiki/Reference/Release_Notes/3.2/Core

#### 参考 Python APIのリリースノートには記述がありませんが、Pythonコンソールでproxyアトリビュートへのアクセスすると3.1.2と3.2RCで以下のように挙動が異なります。
3.1.2
>>> o = bpy.context.active_object
>>> o.proxy
-> no error

3.2RC
>>> o = bpy.context.active_object
>>> o.proxy
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: 'Object' object has no attribute 'proxy'

**Comment by UuuNyaa** [comment]
Thanks for the report and suggestion 😃
I fixed it in e8c2b2b
