### ISSUE TITLE
What do I do?

### ISSUE THREAD

**Issue by Popping3dmodels** [UuuNyaa/blender_mmd_tools#53]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 314, in enable
    importlib.reload(mod)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\__init__.py", line 23, in <module>
    auto_load.init()
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\core\translations.py", line 10, in <module>
    from mmd_tools.core.model import FnModel, Model
ImportError: cannot import name 'FnModel' from 'mmd_tools.core.model' (C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools\core\model.py)

**Comment by UuuNyaa** [comment]
Perhaps the add-on version is out of date; please reinstall the latest add-on.
https://mmd-blender.fandom.com/wiki/MMD_Tools#Installation

**Comment by Popping3dmodels** [comment]
No, it's the current version

**Comment by listelin** [comment]
```
File "C:\Users\micha\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\mmd_tools_init.py", line 23, in
auto_load.init()
```
I think that  "mmd_tools_init.py" is not mmd_tools file.
I don't know why this is happening, deleting thie file may fix this problem.

**Comment by UuuNyaa** [comment]
@listelin Indeed strange file exists... 🤔

@Popping3dmodels Please try reinstalling.
https://mmd-blender.fandom.com/wiki/Why_can%27t_I_reinstall_the_add-ons%3F
