### ISSUE TITLE
Unable to enable the plugin.

### ISSUE THREAD

**Issue by akira0245** [UuuNyaa/blender_mmd_tools#98]
I'm using blender version: 3.5.1, branch: blender-v3.5-release, commit date: 2023-04-24 18:11, hash: e1ccd9d4a1d3, type: release
plugin version 2.8.1

Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\mmd_tools\__init__.py", line 104, in register
    bpy.app.translations.register(bl_info['name'], translation_dict)
ValueError: bpy.app.translations.register: translations message cache already contains some data for addon 'mmd_tools'

**Comment by akira0245** [comment]
Seems like it's conflict with Cats Blender Plugin. after disabled cats plugin i can enable mmd tools now
